In [92]:
import numpy as np
import pandas as pd

In [3]:
file ="/var/www/html/brief11_marché_travail_tech/france_travail.csv"

In [4]:
df = pd.read_csv(file, delimiter = ",",encoding='utf-8')

/tmp/ipykernel_61053/1754498073.py:1: DtypeWarning: Columns (51,53,56,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, delimiter = ",",encoding='utf-8')

In [10]:
df.head()

,id,intitule,description,dateCreation,dateActualisation,lieuTravail_libelle,lieuTravail_latitude,lieuTravail_longitude,lieuTravail_codePostal,lieuTravail_commune,...,contact_courriel,complementExercice,experienceCommentaire,entreprise_logo,langues,contact_urlPostulation,entreprise_url,contact_telephone,conditionExercice,agence_telephone
0,3244435,jardinier H/F - EC21126,jardinier H/F - EC21126 Sous la responsabilité...,2024-09-01T02:51:53.000Z,2024-11-03T02:38:11.000Z,78 - CONFLANS STE HONORINE,49.000025,2.099679,78700.0,78172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3244427,agent développement social référent famille H/...,agent développement social référent famille H/...,2024-09-01T02:51:30.000Z,2024-11-03T02:38:16.000Z,95 - BEZONS,48.927132,2.214879,95870.0,95063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3244363,chargé mission renouvellement urbain H/F - EC2...,chargé mission renouvellement urbain H/F - EC2...,2024-09-01T02:49:40.000Z,2024-11-01T02:54:16.000Z,02 - ST QUENTIN,49.847398,3.287450,2100.0,02691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3244340,médecin généraliste H/F - EC20779,médecin généraliste H/F - EC20779 UNIQUE en so...,2024-09-01T02:49:08.000Z,2024-11-22T02:45:19.000Z,33 - ARCACHON,44.651462,-1.173981,33120.0,33009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3244304,responsable administratif ve H/F - EC9293,responsable administratif ve H/F - EC9293 Miss...,2024-09-01T02:48:24.000Z,2024-11-01T03:00:32.000Z,92 - BAGNEUX,48.797800,2.310213,92220.0,92007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458113 entries, 0 to 458112
Data columns (total 60 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id                            458113 non-null  object
 1   intitule                      458113 non-null  object
 2   description                   458113 non-null  object
 3   dateCreation                  458113 non-null  object
 4   dateActualisation             458113 non-null  object
 5   lieuTravail_libelle           458113 non-null  object
 6   lieuTravail_latitude          408832 non-null  float64
 7   lieuTravail_longitude         408832 non-null  float64
 8   lieuTravail_codePostal        404396 non-null  float64
 9   lieuTravail_commune           407240 non-null  object
 10  romeCode                      458113 non-null  object
 11  romeLibelle                   458113 non-null  object
 12  appellationlibelle            458113 non-null  object
 13  entreprise_nom                305970 non-null  object
 14  entreprise_entrepriseAdaptee  458113 non-null  bool
 15  typeContrat                   458113 non-null  object
 16  typeContratLibelle            458113 non-null  object
 17  natureContrat                 458113 non-null  object
 18  experienceExige               458113 non-null  object
 19  experienceLibelle             458113 non-null  object
 20  alternance                    458113 non-null  bool
 21  nombrePostes                  458113 non-null  int64
 22  accessibleTH                  458113 non-null  bool
 23  origineOffre_origine          458113 non-null  int64
 24  origineOffre_urlOrigine       458113 non-null  object
 25  origineOffre_partenaires      324744 non-null  object
 26  entreprise_description        279551 non-null  object
 27  dureeTravailLibelle           172283 non-null  object
 28  dureeTravailLibelleConverti   158867 non-null  object
 29  codeNAF                       279508 non-null  object
 30  secteurActivite               279508 non-null  float64
 31  secteurActiviteLibelle        279508 non-null  object
 32  salaire_libelle               169597 non-null  object
 33  salaire_commentaire           54279 non-null   object
 34  qualificationCode             154269 non-null  float64
 35  qualificationLibelle          154269 non-null  object
 36  permis                        43625 non-null   object
 37  competences                   107945 non-null  object
 38  salaire_complement1           90219 non-null   object
 39  salaire_complement2           34530 non-null   object
 40  qualitesProfessionnelles      82261 non-null   object
 41  formations                    52329 non-null   object
 42  contact_nom                   94191 non-null   object
 43  contact_coordonnees1          104058 non-null  object
 44  contact_coordonnees2          29165 non-null   object
 45  contact_coordonnees3          29073 non-null   object
 46  agence_courriel               27433 non-null   object
 47  deplacementCode               57955 non-null   float64
 48  deplacementLibelle            58136 non-null   object
 49  offresManqueCandidats         131468 non-null  object
 50  contact_courriel              53035 non-null   object
 51  complementExercice            18626 non-null   object
 52  experienceCommentaire         18709 non-null   object
 53  entreprise_logo               7946 non-null    object
 54  langues                       12307 non-null   object
 55  contact_urlPostulation        21341 non-null   object
 56  entreprise_url                5033 non-null    object
 57  contact_telephone             1477 non-null    float64
 58  conditionExercice             964 non-null     object
 59  agence_telephone              41 non-null      float64
dtypes: bool(3), float64(8), int64(2), object(47)
memory usage: 200.5+ MB

In [13]:
df.columns

Index(['id', 'intitule', 'description', 'dateCreation', 'dateActualisation',
       'lieuTravail_libelle', 'lieuTravail_latitude', 'lieuTravail_longitude',
       'lieuTravail_codePostal', 'lieuTravail_commune', 'romeCode',
       'romeLibelle', 'appellationlibelle', 'entreprise_nom',
       'entreprise_entrepriseAdaptee', 'typeContrat', 'typeContratLibelle',
       'natureContrat', 'experienceExige', 'experienceLibelle', 'alternance',
       'nombrePostes', 'accessibleTH', 'origineOffre_origine',
       'origineOffre_urlOrigine', 'origineOffre_partenaires',
       'entreprise_description', 'dureeTravailLibelle',
       'dureeTravailLibelleConverti', 'codeNAF', 'secteurActivite',
       'secteurActiviteLibelle', 'salaire_libelle', 'salaire_commentaire',
       'qualificationCode', 'qualificationLibelle', 'permis', 'competences',
       'salaire_complement1', 'salaire_complement2',
       'qualitesProfessionnelles', 'formations', 'contact_nom',
       'contact_coordonnees1', 'contact_coordonnees2', 'contact_coordonnees3',
       'agence_courriel', 'deplacementCode', 'deplacementLibelle',
       'offresManqueCandidats', 'contact_courriel', 'complementExercice',
       'experienceCommentaire', 'entreprise_logo', 'langues',
       'contact_urlPostulation', 'entreprise_url', 'contact_telephone',
       'conditionExercice', 'agence_telephone'],
      dtype='object')

In [125]:
new_df = pd.concat([df['id'], df['intitule'], df['description']], axis=1)
nd = pd.DataFrame(new_df)
nd

,id,intitule,description
0,3244435,jardinier H/F - EC21126,jardinier H/F - EC21126 Sous la responsabilité...
1,3244427,agent développement social référent famille H/...,agent développement social référent famille H/...
2,3244363,chargé mission renouvellement urbain H/F - EC2...,chargé mission renouvellement urbain H/F - EC2...
3,3244340,médecin généraliste H/F - EC20779,médecin généraliste H/F - EC20779 UNIQUE en so...
4,3244304,responsable administratif ve H/F - EC9293,responsable administratif ve H/F - EC9293 Miss...
...,...,...,...
458108,7103130,Aide Auxiliaire H/F diplômé(e),1er réseau d'agences de recrutement spécialisé...
458109,7103129,Responsable informatique H/F,Le cabinet Lynx RH recherche un Responsable In...
458110,7103128,CAP PETITE ENFANCE H/F en crèche,Envie de souplesse avec l'intérim ! Vitalis Mé...
458111,7103127,Electromécanicien de maintenance industrielle H/F,Vous êtes passionné par l'électromécanique et ...
458112,7103121,Responsable informatique H/F,Le cabinet Lynx RH recherche un Responsable In...

In [119]:
df['contact_urlPostulation'].value_counts()

contact_urlPostulation
https://www1.ac-grenoble.fr/article/handicap-et-emploi-boe-rqth-121587                                                                        70
https://www.acadomia.fr/enseignant.html#formulaire                                                                                            52
https://www.police-nationale.interieur.gouv.fr/nous-rejoindre/inscriptions-aux-concours-et-selections/policier-adjoint-ouest-sessions-2024    39
https://www.jehann.fr/recrutement                                                                                                             33
https://chelles.candidater.fr/                                                                                                                25
                                                                                                                                              ..
https://taleez.com/apply/agent-de-sterilisation-f-h-selestat-ghso-cdd/applying                                                                 1
https://jobs.smartrecruiters.com/VeoliaEnvironnementSA/743999969369139-technicien-de-maintenance-electricien-f-h                               1
https://www.manpower.fr/emplois/voirOffre?idOffre=1101103773&partenaire=FRANCE_TRAVAIL                                                         1
https://www.edf.fr/edf-recrute/offre/detail/2023-70403                                                                                         1
https://recrutement.education.gouv.fr/recrutement/offreemploi/a1DIV000004M0Th                                                                  1
Name: count, Length: 8896, dtype: int64

In [ ]:
# 458 113 
df['entreprise_nom'].isnull().sum()

np.int64(152143)

In [27]:
df.isnull().sum()

id                                   0
intitule                             0
description                          0
dateCreation                         0
dateActualisation                    0
lieuTravail_libelle                  0
lieuTravail_latitude             49281
lieuTravail_longitude            49281
lieuTravail_codePostal           53717
lieuTravail_commune              50873
romeCode                             0
romeLibelle                          0
appellationlibelle                   0
entreprise_nom                  152143
entreprise_entrepriseAdaptee         0
typeContrat                          0
typeContratLibelle                   0
natureContrat                        0
experienceExige                      0
experienceLibelle                    0
alternance                           0
nombrePostes                         0
accessibleTH                         0
origineOffre_origine                 0
origineOffre_urlOrigine              0
origineOffre_partenaires        133369
entreprise_description          178562
dureeTravailLibelle             285830
dureeTravailLibelleConverti     299246
codeNAF                         178605
secteurActivite                 178605
secteurActiviteLibelle          178605
salaire_libelle                 288516
salaire_commentaire             403834
qualificationCode               303844
qualificationLibelle            303844
permis                          414488
competences                     350168
salaire_complement1             367894
salaire_complement2             423583
qualitesProfessionnelles        375852
formations                      405784
contact_nom                     363922
contact_coordonnees1            354055
contact_coordonnees2            428948
contact_coordonnees3            429040
agence_courriel                 430680
deplacementCode                 400158
deplacementLibelle              399977
offresManqueCandidats           326645
contact_courriel                405078
complementExercice              439487
experienceCommentaire           439404
entreprise_logo                 450167
langues                         445806
contact_urlPostulation          436772
entreprise_url                  453080
contact_telephone               456636
conditionExercice               457149
agence_telephone                458072
dtype: int64

In [68]:
rom = ('M1825', 'M1403')
m18 = df.loc[df['romeCode'].str.startswith(rom)]
m18

,id,intitule,description,dateCreation,dateActualisation,lieuTravail_libelle,lieuTravail_latitude,lieuTravail_longitude,lieuTravail_codePostal,lieuTravail_commune,...,contact_courriel,complementExercice,experienceCommentaire,entreprise_logo,langues,contact_urlPostulation,entreprise_url,contact_telephone,conditionExercice,agence_telephone
380,3317313,Chargé(e) du support - Infrastructures des D...,Nous recherchons pour une entreprise spécialis...,2024-09-03T10:09:53.000Z,2024-09-03T10:09:53.000Z,976 - MAMOUDZOU,-12.797599,45.200869,97600.0,97611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,3317313,Chargé(e) du support - Infrastructures des D...,Nous recherchons pour une entreprise spécialis...,2024-09-03T10:09:53.000Z,2024-09-03T10:09:53.000Z,976 - MAMOUDZOU,-12.797599,45.200869,97600.0,97611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,3317313,Chargé(e) du support - Infrastructures des D...,Nous recherchons pour une entreprise spécialis...,2024-09-03T10:09:53.000Z,2024-09-03T10:09:53.000Z,976 - MAMOUDZOU,-12.797599,45.200869,97600.0,97611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,3338741,Analyste pricing (H/F),Description du poste :\nNotre entreprise\nTu e...,2024-09-03T13:44:39.000Z,2024-11-20T03:12:05.000Z,59 - LILLE,50.630993,3.045449,59000.0,59350,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2464,3479788,Chargé / Chargée d'études en marketing (H/F),"Embarquez avec Start People...CDI, CDD ou Inté...",2024-09-05T07:54:16.000Z,2024-11-16T07:37:38.000Z,44 - CARQUEFOU,47.297116,-1.466824,44470.0,44026,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451227,7096289,Ingénieur d'Etudes VRD (H/F),Société incontournable sur le marché du recrut...,2024-11-06T10:16:05.000Z,2024-11-06T10:16:05.000Z,45 - ORLEANS,47.873507,1.911219,45000.0,45234,...,NaN,Temps plein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451237,7096253,Chargé d'études VRD (H/F),Société incontournable sur le marché du recrut...,2024-11-06T10:15:42.000Z,2024-11-06T10:15:42.000Z,74 - PASSY,45.925787,6.703807,74190.0,74208,...,NaN,Temps plein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451430,7096415,Ingénieur d'études CVC confirmé (H/F),Société incontournable sur le marché du recrut...,2024-11-06T10:17:33.000Z,2024-11-06T10:17:33.000Z,92 - ANTONY,48.751021,2.297830,92160.0,92002,...,NaN,Temps plein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451436,7096397,Ingénieur d'Etudes Aménagements urbains (H/F),Société incontournable sur le marché du recrut...,2024-11-06T10:17:22.000Z,2024-11-06T10:17:22.000Z,84 - LE PONTET,43.970186,4.865857,84130.0,84092,...,NaN,Temps plein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451453,7096344,Ingénieur d'Etudes VRD (H/F),Société incontournable sur le marché du recrut...,2024-11-06T10:16:47.000Z,2024-11-06T10:16:47.000Z,34 - BEZIERS,43.343264,3.233465,34500.0,34032,...,NaN,Temps plein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN